## ==========================================================================================================================================================================================================================
##
## R code to generate Figure 4 for manuscript titled "How public reaction to disease information across scales and the impacts of vector control methods influence disease prevalence and control efficacy"

## ==================================================================================================================================================================================================================


############################################################
## R packages installed and open
library(ggplot2)
library(reshape)
library(here)

## set the current directory as default to save all the following results
set_here()

cont = seq(0,200,20) # set up levels regarding the control on mosquito larvae
adultprop <- cont/max(cont)
larvaeprop <- 1 - adultprop
rep <- 30  # number of levels
N = 9 # total patch number
replic = 30  # repeat for each control level

confidence_interval <- function(vector, interval) {
  # Standard deviation of sample
  vec_sd <- sd(vector)
  # Sample size
  n <- length(vector)
  # Mean of sample
  vec_mean <- mean(vector)
  # Error according to t distribution
  error <- qt((interval + 1)/2, df = n - 1) * vec_sd / sqrt(n)
  # Confidence interval as a vector
  result <- c("lower" = vec_mean - error, "upper" = vec_mean + error)
  return(result)
}

############################################################

## read datasets csv with control at 3 information levels and 3 breeding capacity levels, which can be modified and generated by Matlab code "Figure_4.m"

## All csv. files in No Control section can be generated by Matlab Code "Multi_Patch_NoControl". 

setwd("C:\\Users\\lucyj\\Documents\\New folder\\Zika Project\\SF-local-N-9-p-0.01-t-1000-K=2000-time+strength+control")

KT2000localinfection <- read.csv("2-a1--a2--g1--g2--e1--e2--INFECTED-HUMANS.csv",header=FALSE,stringsAsFactors = FALSE)
KT2000localCIdistance <- read.csv("2-a1--a2--g1--g2--e1--e2--DISTANCE-PATCH.csv",header = FALSE)
KT2000localcontrollarvae <- read.csv("2-a1--a2--g1--g2--e1--e2--PESTICICDES-LARVAE.csv",header=FALSE)
KT2000localcontroladult <- read.csv("2-a1--a2--g1--g2--e1--e2--PESTICIDES-ADULTS.csv", header=FALSE)


#############################################################

# group all orginal datasets according to the levels of control on larvae
# 
KK <- c()
for ( i in 1:dim(KT2000localcontrollarvae)[1])
{
  if (KT2000localcontrollarvae[i,1] == 0)
    KK <- c(KK, i)
}

KK_new <- c(KK, dim(KT2000localcontrollarvae)[1]+1)
# 

#################################################################

##level 1

################################################################

i = 1

epsilon <- c(cont[i]+0.0001, 200.0001-cont[i])

ind <- KK_new[(replic * (i - 1) + 1) : (replic * i + 1)]


KT2000localinfect <- KT2000localinfection[ind[1]:(ind[length(ind)]-1), ]

KT2000localadultcontrol <- KT2000localcontroladult[ind[1]:(ind[length(ind)]-1), ]

KT2000locallarvaecontrol <- KT2000localcontrollarvae[ind[1]:(ind[length(ind)]-1), ]

KT2000localCIdistancenew <- KT2000localCIdistance[(replic * (i - 1) + 1): (replic * i),]


KK<-c()
for ( i in 1:dim(KT2000localadultcontrol)[1])
{
  if (KT2000localadultcontrol[i,1]==0)
    KK <-c(KK, i)
}

lastlength <- dim(KT2000localadultcontrol)[1]-KK[length(KK)]+1
diff <- c(diff(KK), lastlength)

KT2000localmeanInfectiontotal<-matrix(, nrow = rep, ncol = max(diff))
KT2000localmeanControltotal<-matrix(, nrow = rep, ncol = max(diff))

index <- which.max(diff)

if(index < rep)
{
  x_axis_KT2000_local <- KT2000localadultcontrol[KK[index]:(KK[index+1]-1),1]
} else
{
  x_axis_KT2000_local <-KT2000localadultcontrol[KK[rep]:dim(KT2000localadultcontrol)[1],1]
}


for (i in 1:(rep-1))
{
  
  KT2000localdataset0 <- KT2000localinfect[KK[i]:(KK[i+1]-1),]
  KT2000localdataset1 <- KT2000locallarvaecontrol[KK[i]:(KK[i+1]-1),]
  KT2000localdataset2 <- KT2000localadultcontrol[KK[i]:(KK[i+1]-1),]
  KT2000localdata0 <- KT2000localdataset0[,-(which.min(KT2000localCIdistancenew[i,])+1)]
  KT2000localdataControl1 <- KT2000localdataset1[,-(which.min(KT2000localCIdistancenew[i,])+1)] 
  KT2000localdataControl2 <- KT2000localdataset2[,-(which.min(KT2000localCIdistancenew[i,])+1)] 
  ##this 1 is the time column
  KT2000localmeanInfectionSum <- as.vector(rowSums(KT2000localdata0[,2:ncol(KT2000localdata0)])/(N-1))
  KT2000localmeanControlsum <- as.vector(rowSums(1*KT2000localdataControl1[,2:ncol(KT2000localdataControl1)]+1*KT2000localdataControl2[,2:ncol(KT2000localdataControl2)])/(N-1))
  KT2000localmeanControlsum1<-approx(KT2000localdataControl1[,1],KT2000localmeanControlsum, x_axis_KT2000_local)$y
  
  KT2000localmeanInfectiontotal[i,]<-KT2000localmeanInfectionSum
  KT2000localmeanControltotal[i,]<-KT2000localmeanControlsum1
  
}

##last row of KT2000localmeanadultcontrol
KT2000localdataset0 <- KT2000localinfect[KK[rep]:attributes(as.matrix(KT2000locallarvaecontrol))$dim[1],]
KT2000localdataset1 <- KT2000locallarvaecontrol[KK[rep]:attributes(as.matrix(KT2000locallarvaecontrol))$dim[1],]
KT2000localdataset2 <- KT2000localadultcontrol[KK[rep]:attributes(as.matrix(KT2000localadultcontrol))$dim[1],]
KT2000localdata0 <- KT2000localdataset0[,-(which.min(KT2000localCIdistancenew[rep,])+1)] 

KT2000localdataControl1 <- KT2000localdataset1[,-(which.min(KT2000localCIdistancenew[rep,])+1)] 

KT2000localdataControl2 <- KT2000localdataset2[,-(which.min(KT2000localCIdistancenew[rep,])+1)] 
##this 1 is the time column
KT2000localmeanInfectionSum <- as.vector(rowSums(KT2000localdata0[,2:ncol(KT2000localdata0)])/(N-1))
KT2000localmeanControlsum <- as.vector(rowSums(1*KT2000localdataControl1[,2:ncol(KT2000localdataControl1)]+1*KT2000localdataControl2[,2:ncol(KT2000localdataControl2)])/(N-1))
KT2000localmeanControlsum1<-approx(KT2000localdataControl1[,1],KT2000localmeanControlsum, x_axis_KT2000_local)$y

KT2000localmeanInfectiontotal[rep,]<-KT2000localmeanInfectionSum
KT2000localmeanControltotal[rep,]<-KT2000localmeanControlsum1

KT2000localaverageInfection <- colSums(KT2000localmeanInfectiontotal)/rep

KT2000localaverageControl <- colSums(KT2000localmeanControltotal)/rep

KT2000localControlCIlow<-c()
KT2000localControlCIhigh<-c()

for(i in 1:length(KT2000localaverageControl))
{
  KT2000localControlCIlow[i]<-confidence_interval(KT2000localmeanControltotal[,i], 0.95)[1][[1]]
  KT2000localControlCIhigh[i]<-confidence_interval(KT2000localmeanControltotal[,i],0.95)[2][[1]]
}

## assign the level

CI_low_KT2000_local_control_1 <- KT2000localControlCIlow
CI_high_KT2000_local_control_1 <- KT2000localControlCIhigh
ave_KT2000_local_infection_1 <- KT2000localaverageInfection
ave_KT2000_local_control_1 <- KT2000localaverageControl
x_axis_KT2000_local_1 <- x_axis_KT2000_local


#####################################################

# for level 2

#####################################################

i = 2

epsilon <- c(cont[i]+0.0001, 200.0001-cont[i])

ind <- KK_new[(replic * (i - 1) + 1) : (replic * i + 1)]


KT2000localinfect <- KT2000localinfection[ind[1]:(ind[length(ind)]-1), ]

KT2000localadultcontrol <- KT2000localcontroladult[ind[1]:(ind[length(ind)]-1), ]

KT2000locallarvaecontrol <- KT2000localcontrollarvae[ind[1]:(ind[length(ind)]-1), ]

KT2000localCIdistancenew <- KT2000localCIdistance[(replic * (i - 1) + 1): (replic * i),]


KK<-c()
for ( i in 1:dim(KT2000localadultcontrol)[1])
{
  if (KT2000localadultcontrol[i,1]==0)
    KK <-c(KK, i)
}

lastlength <- dim(KT2000localadultcontrol)[1]-KK[length(KK)]+1
diff <- c(diff(KK), lastlength)

KT2000localmeanInfectiontotal<-matrix(, nrow = rep, ncol = max(diff))
KT2000localmeanControltotal<-matrix(, nrow = rep, ncol = max(diff))

index <- which.max(diff)

if(index < rep)
{
  x_axis_KT2000_local <- KT2000localadultcontrol[KK[index]:(KK[index+1]-1),1]
} else
{
  x_axis_KT2000_local <-KT2000localadultcontrol[KK[rep]:dim(KT2000localadultcontrol)[1],1]
}


for (i in 1:(rep-1))
{
  
  KT2000localdataset0 <- KT2000localinfect[KK[i]:(KK[i+1]-1),]
  KT2000localdataset1 <- KT2000locallarvaecontrol[KK[i]:(KK[i+1]-1),]
  KT2000localdataset2 <- KT2000localadultcontrol[KK[i]:(KK[i+1]-1),]
  KT2000localdata0 <- KT2000localdataset0[,-(which.min(KT2000localCIdistancenew[i,])+1)]
  KT2000localdataControl1 <- KT2000localdataset1[,-(which.min(KT2000localCIdistancenew[i,])+1)] 
  KT2000localdataControl2 <- KT2000localdataset2[,-(which.min(KT2000localCIdistancenew[i,])+1)] 
  ##this 1 is the time column
  KT2000localmeanInfectionSum <- as.vector(rowSums(KT2000localdata0[,2:ncol(KT2000localdata0)])/(N-1))
  KT2000localmeanControlsum <- as.vector(rowSums(1*KT2000localdataControl1[,2:ncol(KT2000localdataControl1)]+1*KT2000localdataControl2[,2:ncol(KT2000localdataControl2)])/(N-1))
  KT2000localmeanControlsum1<-approx(KT2000localdataControl1[,1],KT2000localmeanControlsum, x_axis_KT2000_local)$y
  
  KT2000localmeanInfectiontotal[i,]<-KT2000localmeanInfectionSum
  KT2000localmeanControltotal[i,]<-KT2000localmeanControlsum1
}

##last row of KT2000localmeanadultcontrol
KT2000localdataset0 <- KT2000localinfect[KK[rep]:attributes(as.matrix(KT2000locallarvaecontrol))$dim[1],]
KT2000localdataset1 <- KT2000locallarvaecontrol[KK[rep]:attributes(as.matrix(KT2000locallarvaecontrol))$dim[1],]
KT2000localdataset2 <- KT2000localadultcontrol[KK[rep]:attributes(as.matrix(KT2000localadultcontrol))$dim[1],]
KT2000localdata0 <- KT2000localdataset0[,-(which.min(KT2000localCIdistancenew[rep,])+1)] 

KT2000localdataControl1 <- KT2000localdataset1[,-(which.min(KT2000localCIdistancenew[rep,])+1)] 

KT2000localdataControl2 <- KT2000localdataset2[,-(which.min(KT2000localCIdistancenew[rep,])+1)] 
##this 1 is the time column
KT2000localmeanInfectionSum <- as.vector(rowSums(KT2000localdata0[,2:ncol(KT2000localdata0)])/(N-1))
KT2000localmeanControlsum <- as.vector(rowSums(1*KT2000localdataControl1[,2:ncol(KT2000localdataControl1)]+1*KT2000localdataControl2[,2:ncol(KT2000localdataControl2)])/(N-1))
KT2000localmeanControlsum1<-approx(KT2000localdataControl1[,1],KT2000localmeanControlsum, x_axis_KT2000_local)$y

KT2000localmeanInfectiontotal[rep,]<-KT2000localmeanInfectionSum
KT2000localmeanControltotal[rep,]<-KT2000localmeanControlsum1

KT2000localaverageInfection <- colSums(KT2000localmeanInfectiontotal)/rep

KT2000localaverageControl <- colSums(KT2000localmeanControltotal)/rep

KT2000localControlCIlow<-c()
KT2000localControlCIhigh<-c()

for(i in 1:length(KT2000localaverageControl))
{
  KT2000localControlCIlow[i]<-confidence_interval(KT2000localmeanControltotal[,i], 0.95)[1][[1]]
  KT2000localControlCIhigh[i]<-confidence_interval(KT2000localmeanControltotal[,i],0.95)[2][[1]]
}

## assign the level

CI_low_KT2000_local_control_2 <- KT2000localControlCIlow
CI_high_KT2000_local_control_2 <- KT2000localControlCIhigh
ave_KT2000_local_control_2 <- KT2000localaverageControl
ave_KT2000_local_infection_2 <- KT2000localaverageInfection
x_axis_KT2000_local_2 <- x_axis_KT2000_local


########################################################

##level 3

########################################################

i = 3

epsilon <- c(cont[i]+0.0001, 200.0001-cont[i])

ind <- KK_new[(replic * (i - 1) + 1) : (replic * i + 1)]


KT2000localinfect <- KT2000localinfection[ind[1]:(ind[length(ind)]-1), ]

KT2000localadultcontrol <- KT2000localcontroladult[ind[1]:(ind[length(ind)]-1), ]

KT2000locallarvaecontrol <- KT2000localcontrollarvae[ind[1]:(ind[length(ind)]-1), ]

KT2000localCIdistancenew <- KT2000localCIdistance[(replic * (i - 1) + 1): (replic * i),]


KK<-c()
for ( i in 1:dim(KT2000localadultcontrol)[1])
{
  if (KT2000localadultcontrol[i,1]==0)
    KK <-c(KK, i)
}

lastlength <- dim(KT2000localadultcontrol)[1]-KK[length(KK)]+1
diff <- c(diff(KK), lastlength)

KT2000localmeanInfectiontotal<-matrix(, nrow = rep, ncol = max(diff))
KT2000localmeanControltotal<-matrix(, nrow = rep, ncol = max(diff))

index <- which.max(diff)

if(index < rep)
{
  x_axis_KT2000_local <- KT2000localadultcontrol[KK[index]:(KK[index+1]-1),1]
} else
{
  x_axis_KT2000_local <-KT2000localadultcontrol[KK[rep]:dim(KT2000localadultcontrol)[1],1]
}


for (i in 1:(rep-1))
{
  
  KT2000localdataset0 <- KT2000localinfect[KK[i]:(KK[i+1]-1),]
  KT2000localdataset1 <- KT2000locallarvaecontrol[KK[i]:(KK[i+1]-1),]
  KT2000localdataset2 <- KT2000localadultcontrol[KK[i]:(KK[i+1]-1),]
  KT2000localdata0 <- KT2000localdataset0[,-(which.min(KT2000localCIdistancenew[i,])+1)]
  KT2000localdataControl1 <- KT2000localdataset1[,-(which.min(KT2000localCIdistancenew[i,])+1)] 
  KT2000localdataControl2 <- KT2000localdataset2[,-(which.min(KT2000localCIdistancenew[i,])+1)] 
  ##this 1 is the time column
  KT2000localmeanInfectionSum <- as.vector(rowSums(KT2000localdata0[,2:ncol(KT2000localdata0)])/(N-1))
  KT2000localmeanControlsum <- as.vector(rowSums(1*KT2000localdataControl1[,2:ncol(KT2000localdataControl1)]+1*KT2000localdataControl2[,2:ncol(KT2000localdataControl2)])/(N-1))
  KT2000localmeanControlsum1<-approx(KT2000localdataControl1[,1],KT2000localmeanControlsum, x_axis_KT2000_local)$y
  
  KT2000localmeanInfectiontotal[i,]<-KT2000localmeanInfectionSum
  KT2000localmeanControltotal[i,]<-KT2000localmeanControlsum1
}

##last row of KT2000localmeanadultcontrol
KT2000localdataset0 <- KT2000localinfect[KK[rep]:attributes(as.matrix(KT2000locallarvaecontrol))$dim[1],]
KT2000localdataset1 <- KT2000locallarvaecontrol[KK[rep]:attributes(as.matrix(KT2000locallarvaecontrol))$dim[1],]
KT2000localdataset2 <- KT2000localadultcontrol[KK[rep]:attributes(as.matrix(KT2000localadultcontrol))$dim[1],]
KT2000localdata0 <- KT2000localdataset0[,-(which.min(KT2000localCIdistancenew[rep,])+1)] 

KT2000localdataControl1 <- KT2000localdataset1[,-(which.min(KT2000localCIdistancenew[rep,])+1)] 

KT2000localdataControl2 <- KT2000localdataset2[,-(which.min(KT2000localCIdistancenew[rep,])+1)] 
##this 1 is the time column
KT2000localmeanInfectionSum <- as.vector(rowSums(KT2000localdata0[,2:ncol(KT2000localdata0)])/(N-1))
KT2000localmeanControlsum <- as.vector(rowSums(1*KT2000localdataControl1[,2:ncol(KT2000localdataControl1)]+1*KT2000localdataControl2[,2:ncol(KT2000localdataControl2)])/(N-1))
KT2000localmeanControlsum1<-approx(KT2000localdataControl1[,1],KT2000localmeanControlsum, x_axis_KT2000_local)$y

KT2000localmeanInfectiontotal[rep,]<-KT2000localmeanInfectionSum
KT2000localmeanControltotal[rep,]<-KT2000localmeanControlsum1

KT2000localaverageInfection <- colSums(KT2000localmeanInfectiontotal)/rep

KT2000localaverageControl <- colSums(KT2000localmeanControltotal)/rep

KT2000localControlCIlow<-c()
KT2000localControlCIhigh<-c()

for(i in 1:length(KT2000localaverageControl))
{
  KT2000localControlCIlow[i]<-confidence_interval(KT2000localmeanControltotal[,i], 0.95)[1][[1]]
  KT2000localControlCIhigh[i]<-confidence_interval(KT2000localmeanControltotal[,i],0.95)[2][[1]]
}

## assign the level

CI_low_KT2000_local_control_3 <- KT2000localControlCIlow
CI_high_KT2000_local_control_3 <- KT2000localControlCIhigh
ave_KT2000_local_control_3 <- KT2000localaverageControl
ave_KT2000_local_infection_3 <- KT2000localaverageInfection
x_axis_KT2000_local_3 <- x_axis_KT2000_local


###################################################################

##level 4

###################################################################


i = 4

epsilon <- c(cont[i]+0.0001, 200.0001-cont[i])

ind <- KK_new[(replic * (i - 1) + 1) : (replic * i + 1)]


KT2000localinfect <- KT2000localinfection[ind[1]:(ind[length(ind)]-1), ]

KT2000localadultcontrol <- KT2000localcontroladult[ind[1]:(ind[length(ind)]-1), ]

KT2000locallarvaecontrol <- KT2000localcontrollarvae[ind[1]:(ind[length(ind)]-1), ]

KT2000localCIdistancenew <- KT2000localCIdistance[(replic * (i - 1) + 1): (replic * i),]


KK<-c()
for ( i in 1:dim(KT2000localadultcontrol)[1])
{
  if (KT2000localadultcontrol[i,1]==0)
    KK <-c(KK, i)
}

lastlength <- dim(KT2000localadultcontrol)[1]-KK[length(KK)]+1
diff <- c(diff(KK), lastlength)

KT2000localmeanInfectiontotal<-matrix(, nrow = rep, ncol = max(diff))
KT2000localmeanControltotal<-matrix(, nrow = rep, ncol = max(diff))

index <- which.max(diff)

if(index < rep)
{
  x_axis_KT2000_local <- KT2000localadultcontrol[KK[index]:(KK[index+1]-1),1]
} else
{
  x_axis_KT2000_local <-KT2000localadultcontrol[KK[rep]:dim(KT2000localadultcontrol)[1],1]
}


for (i in 1:(rep-1))
{
  
  KT2000localdataset0 <- KT2000localinfect[KK[i]:(KK[i+1]-1),]
  KT2000localdataset1 <- KT2000locallarvaecontrol[KK[i]:(KK[i+1]-1),]
  KT2000localdataset2 <- KT2000localadultcontrol[KK[i]:(KK[i+1]-1),]
  KT2000localdata0 <- KT2000localdataset0[,-(which.min(KT2000localCIdistancenew[i,])+1)]
  KT2000localdataControl1 <- KT2000localdataset1[,-(which.min(KT2000localCIdistancenew[i,])+1)] 
  KT2000localdataControl2 <- KT2000localdataset2[,-(which.min(KT2000localCIdistancenew[i,])+1)] 
  ##this 1 is the time column
  KT2000localmeanInfectionSum <- as.vector(rowSums(KT2000localdata0[,2:ncol(KT2000localdata0)])/(N-1))
  KT2000localmeanControlsum <- as.vector(rowSums(1*KT2000localdataControl1[,2:ncol(KT2000localdataControl1)]+1*KT2000localdataControl2[,2:ncol(KT2000localdataControl2)])/(N-1))
  KT2000localmeanControlsum1<-approx(KT2000localdataControl1[,1],KT2000localmeanControlsum, x_axis_KT2000_local)$y
  
  KT2000localmeanInfectiontotal[i,]<-KT2000localmeanInfectionSum
  KT2000localmeanControltotal[i,]<-KT2000localmeanControlsum1
}

##last row of KT2000localmeanadultcontrol
KT2000localdataset0 <- KT2000localinfect[KK[rep]:attributes(as.matrix(KT2000locallarvaecontrol))$dim[1],]
KT2000localdataset1 <- KT2000locallarvaecontrol[KK[rep]:attributes(as.matrix(KT2000locallarvaecontrol))$dim[1],]
KT2000localdataset2 <- KT2000localadultcontrol[KK[rep]:attributes(as.matrix(KT2000localadultcontrol))$dim[1],]
KT2000localdata0 <- KT2000localdataset0[,-(which.min(KT2000localCIdistancenew[rep,])+1)] 

KT2000localdataControl1 <- KT2000localdataset1[,-(which.min(KT2000localCIdistancenew[rep,])+1)] 

KT2000localdataControl2 <- KT2000localdataset2[,-(which.min(KT2000localCIdistancenew[rep,])+1)] 
##this 1 is the time column
KT2000localmeanInfectionSum <- as.vector(rowSums(KT2000localdata0[,2:ncol(KT2000localdata0)])/(N-1))
KT2000localmeanControlsum <- as.vector(rowSums(1*KT2000localdataControl1[,2:ncol(KT2000localdataControl1)]+1*KT2000localdataControl2[,2:ncol(KT2000localdataControl2)])/(N-1))
KT2000localmeanControlsum1<-approx(KT2000localdataControl1[,1],KT2000localmeanControlsum, x_axis_KT2000_local)$y

KT2000localmeanInfectiontotal[rep,]<-KT2000localmeanInfectionSum
KT2000localmeanControltotal[rep,]<-KT2000localmeanControlsum1

KT2000localaverageInfection <- colSums(KT2000localmeanInfectiontotal)/rep

KT2000localaverageControl <- colSums(KT2000localmeanControltotal)/rep

KT2000localControlCIlow<-c()
KT2000localControlCIhigh<-c()

for(i in 1:length(KT2000localaverageControl))
{
  KT2000localControlCIlow[i]<-confidence_interval(KT2000localmeanControltotal[,i], 0.95)[1][[1]]
  KT2000localControlCIhigh[i]<-confidence_interval(KT2000localmeanControltotal[,i],0.95)[2][[1]]
}

## assign the level

CI_low_KT2000_local_control_4 <- KT2000localControlCIlow
CI_high_KT2000_local_control_4 <- KT2000localControlCIhigh
ave_KT2000_local_control_4 <- KT2000localaverageControl
ave_KT2000_local_infection_4 <- KT2000localaverageInfection
x_axis_KT2000_local_4 <- x_axis_KT2000_local

################################################################

## level 5

################################################################


i = 5

epsilon <- c(cont[i]+0.0001, 200.0001-cont[i])

ind <- KK_new[(replic * (i - 1) + 1) : (replic * i + 1)]


KT2000localinfect <- KT2000localinfection[ind[1]:(ind[length(ind)]-1), ]

KT2000localadultcontrol <- KT2000localcontroladult[ind[1]:(ind[length(ind)]-1), ]

KT2000locallarvaecontrol <- KT2000localcontrollarvae[ind[1]:(ind[length(ind)]-1), ]

KT2000localCIdistancenew <- KT2000localCIdistance[(replic * (i - 1) + 1): (replic * i),]


KK<-c()
for ( i in 1:dim(KT2000localadultcontrol)[1])
{
  if (KT2000localadultcontrol[i,1]==0)
    KK <-c(KK, i)
}

lastlength <- dim(KT2000localadultcontrol)[1]-KK[length(KK)]+1
diff <- c(diff(KK), lastlength)

KT2000localmeanInfectiontotal<-matrix(, nrow = rep, ncol = max(diff))
KT2000localmeanControltotal<-matrix(, nrow = rep, ncol = max(diff))

index <- which.max(diff)

if(index < rep)
{
  x_axis_KT2000_local <- KT2000localadultcontrol[KK[index]:(KK[index+1]-1),1]
} else
{
  x_axis_KT2000_local <-KT2000localadultcontrol[KK[rep]:dim(KT2000localadultcontrol)[1],1]
}


for (i in 1:(rep-1))
{
  
  KT2000localdataset0 <- KT2000localinfect[KK[i]:(KK[i+1]-1),]
  KT2000localdataset1 <- KT2000locallarvaecontrol[KK[i]:(KK[i+1]-1),]
  KT2000localdataset2 <- KT2000localadultcontrol[KK[i]:(KK[i+1]-1),]
  KT2000localdata0 <- KT2000localdataset0[,-(which.min(KT2000localCIdistancenew[i,])+1)]
  KT2000localdataControl1 <- KT2000localdataset1[,-(which.min(KT2000localCIdistancenew[i,])+1)] 
  KT2000localdataControl2 <- KT2000localdataset2[,-(which.min(KT2000localCIdistancenew[i,])+1)] 
  ##this 1 is the time column
  KT2000localmeanInfectionSum <- as.vector(rowSums(KT2000localdata0[,2:ncol(KT2000localdata0)])/(N-1))
  KT2000localmeanControlsum <- as.vector(rowSums(1*KT2000localdataControl1[,2:ncol(KT2000localdataControl1)]+1*KT2000localdataControl2[,2:ncol(KT2000localdataControl2)])/(N-1))
  KT2000localmeanControlsum1<-approx(KT2000localdataControl1[,1],KT2000localmeanControlsum, x_axis_KT2000_local)$y
  
  KT2000localmeanInfectiontotal[i,]<-KT2000localmeanInfectionSum
  KT2000localmeanControltotal[i,]<-KT2000localmeanControlsum1
}

##last row of KT2000localmeanadultcontrol
KT2000localdataset0 <- KT2000localinfect[KK[rep]:attributes(as.matrix(KT2000locallarvaecontrol))$dim[1],]
KT2000localdataset1 <- KT2000locallarvaecontrol[KK[rep]:attributes(as.matrix(KT2000locallarvaecontrol))$dim[1],]
KT2000localdataset2 <- KT2000localadultcontrol[KK[rep]:attributes(as.matrix(KT2000localadultcontrol))$dim[1],]
KT2000localdata0 <- KT2000localdataset0[,-(which.min(KT2000localCIdistancenew[rep,])+1)] 

KT2000localdataControl1 <- KT2000localdataset1[,-(which.min(KT2000localCIdistancenew[rep,])+1)] 

KT2000localdataControl2 <- KT2000localdataset2[,-(which.min(KT2000localCIdistancenew[rep,])+1)] 
##this 1 is the time column
KT2000localmeanInfectionSum <- as.vector(rowSums(KT2000localdata0[,2:ncol(KT2000localdata0)])/(N-1))
KT2000localmeanControlsum <- as.vector(rowSums(1*KT2000localdataControl1[,2:ncol(KT2000localdataControl1)]+1*KT2000localdataControl2[,2:ncol(KT2000localdataControl2)])/(N-1))
KT2000localmeanControlsum1<-approx(KT2000localdataControl1[,1],KT2000localmeanControlsum, x_axis_KT2000_local)$y

KT2000localmeanInfectiontotal[rep,]<-KT2000localmeanInfectionSum
KT2000localmeanControltotal[rep,]<-KT2000localmeanControlsum1

KT2000localaverageInfection <- colSums(KT2000localmeanInfectiontotal)/rep

KT2000localaverageControl <- colSums(KT2000localmeanControltotal)/rep

KT2000localControlCIlow<-c()
KT2000localControlCIhigh<-c()

for(i in 1:length(KT2000localaverageControl))
{
  KT2000localControlCIlow[i]<-confidence_interval(KT2000localmeanControltotal[,i], 0.95)[1][[1]]
  KT2000localControlCIhigh[i]<-confidence_interval(KT2000localmeanControltotal[,i],0.95)[2][[1]]
}

## assign the level

CI_low_KT2000_local_control_5 <- KT2000localControlCIlow
CI_high_KT2000_local_control_5 <- KT2000localControlCIhigh
ave_KT2000_local_control_5 <- KT2000localaverageControl
ave_KT2000_local_infection_5 <- KT2000localaverageInfection
x_axis_KT2000_local_5 <- x_axis_KT2000_local

####################################################################

##level 6

###################################################################


i = 6

epsilon <- c(cont[i]+0.0001, 200.0001-cont[i])

ind <- KK_new[(replic * (i - 1) + 1) : (replic * i + 1)]


KT2000localinfect <- KT2000localinfection[ind[1]:(ind[length(ind)]-1), ]

KT2000localadultcontrol <- KT2000localcontroladult[ind[1]:(ind[length(ind)]-1), ]

KT2000locallarvaecontrol <- KT2000localcontrollarvae[ind[1]:(ind[length(ind)]-1), ]

KT2000localCIdistancenew <- KT2000localCIdistance[(replic * (i - 1) + 1): (replic * i),]


KK<-c()
for ( i in 1:dim(KT2000localadultcontrol)[1])
{
  if (KT2000localadultcontrol[i,1]==0)
    KK <-c(KK, i)
}

lastlength <- dim(KT2000localadultcontrol)[1]-KK[length(KK)]+1
diff <- c(diff(KK), lastlength)

KT2000localmeanInfectiontotal<-matrix(, nrow = rep, ncol = max(diff))
KT2000localmeanControltotal<-matrix(, nrow = rep, ncol = max(diff))

index <- which.max(diff)

if(index < rep)
{
  x_axis_KT2000_local <- KT2000localadultcontrol[KK[index]:(KK[index+1]-1),1]
} else
{
  x_axis_KT2000_local <-KT2000localadultcontrol[KK[rep]:dim(KT2000localadultcontrol)[1],1]
}


for (i in 1:(rep-1))
{
  
  KT2000localdataset0 <- KT2000localinfect[KK[i]:(KK[i+1]-1),]
  KT2000localdataset1 <- KT2000locallarvaecontrol[KK[i]:(KK[i+1]-1),]
  KT2000localdataset2 <- KT2000localadultcontrol[KK[i]:(KK[i+1]-1),]
  KT2000localdata0 <- KT2000localdataset0[,-(which.min(KT2000localCIdistancenew[i,])+1)]
  KT2000localdataControl1 <- KT2000localdataset1[,-(which.min(KT2000localCIdistancenew[i,])+1)] 
  KT2000localdataControl2 <- KT2000localdataset2[,-(which.min(KT2000localCIdistancenew[i,])+1)] 
  ##this 1 is the time column
  KT2000localmeanInfectionSum <- as.vector(rowSums(KT2000localdata0[,2:ncol(KT2000localdata0)])/(N-1))
  KT2000localmeanControlsum <- as.vector(rowSums(1*KT2000localdataControl1[,2:ncol(KT2000localdataControl1)]+1*KT2000localdataControl2[,2:ncol(KT2000localdataControl2)])/(N-1))
  KT2000localmeanControlsum1<-approx(KT2000localdataControl1[,1],KT2000localmeanControlsum, x_axis_KT2000_local)$y
  
  KT2000localmeanInfectiontotal[i,]<-KT2000localmeanInfectionSum
  KT2000localmeanControltotal[i,]<-KT2000localmeanControlsum1
}

##last row of KT2000localmeanadultcontrol
KT2000localdataset0 <- KT2000localinfect[KK[rep]:attributes(as.matrix(KT2000locallarvaecontrol))$dim[1],]
KT2000localdataset1 <- KT2000locallarvaecontrol[KK[rep]:attributes(as.matrix(KT2000locallarvaecontrol))$dim[1],]
KT2000localdataset2 <- KT2000localadultcontrol[KK[rep]:attributes(as.matrix(KT2000localadultcontrol))$dim[1],]
KT2000localdata0 <- KT2000localdataset0[,-(which.min(KT2000localCIdistancenew[rep,])+1)] 

KT2000localdataControl1 <- KT2000localdataset1[,-(which.min(KT2000localCIdistancenew[rep,])+1)] 

KT2000localdataControl2 <- KT2000localdataset2[,-(which.min(KT2000localCIdistancenew[rep,])+1)] 
##this 1 is the time column
KT2000localmeanInfectionSum <- as.vector(rowSums(KT2000localdata0[,2:ncol(KT2000localdata0)])/(N-1))
KT2000localmeanControlsum <- as.vector(rowSums(1*KT2000localdataControl1[,2:ncol(KT2000localdataControl1)]+1*KT2000localdataControl2[,2:ncol(KT2000localdataControl2)])/(N-1))
KT2000localmeanControlsum1<-approx(KT2000localdataControl1[,1],KT2000localmeanControlsum, x_axis_KT2000_local)$y

KT2000localmeanInfectiontotal[rep,]<-KT2000localmeanInfectionSum
KT2000localmeanControltotal[rep,]<-KT2000localmeanControlsum1

KT2000localaverageInfection <- colSums(KT2000localmeanInfectiontotal)/rep

KT2000localaverageControl <- colSums(KT2000localmeanControltotal)/rep

KT2000localControlCIlow<-c()
KT2000localControlCIhigh<-c()

for(i in 1:length(KT2000localaverageControl))
{
  KT2000localControlCIlow[i]<-confidence_interval(KT2000localmeanControltotal[,i], 0.95)[1][[1]]
  KT2000localControlCIhigh[i]<-confidence_interval(KT2000localmeanControltotal[,i],0.95)[2][[1]]
}

## assign the level

CI_low_KT2000_local_control_6 <- KT2000localControlCIlow
CI_high_KT2000_local_control_6 <- KT2000localControlCIhigh
ave_KT2000_local_control_6 <- KT2000localaverageControl
ave_KT2000_local_infection_6 <- KT2000localaverageInfection
x_axis_KT2000_local_6 <- x_axis_KT2000_local

##############################################################

# ## level 7
#
# #############################################################


i = 7

epsilon <- c(cont[i]+0.0001, 200.0001-cont[i])

ind <- KK_new[(replic * (i - 1) + 1) : (replic * i + 1)]


KT2000localinfect <- KT2000localinfection[ind[1]:(ind[length(ind)]-1), ]

KT2000localadultcontrol <- KT2000localcontroladult[ind[1]:(ind[length(ind)]-1), ]

KT2000locallarvaecontrol <- KT2000localcontrollarvae[ind[1]:(ind[length(ind)]-1), ]

KT2000localCIdistancenew <- KT2000localCIdistance[(replic * (i - 1) + 1): (replic * i),]


KK<-c()
for ( i in 1:dim(KT2000localadultcontrol)[1])
{
  if (KT2000localadultcontrol[i,1]==0)
    KK <-c(KK, i)
}

lastlength <- dim(KT2000localadultcontrol)[1]-KK[length(KK)]+1
diff <- c(diff(KK), lastlength)

KT2000localmeanInfectiontotal<-matrix(, nrow = rep, ncol = max(diff))
KT2000localmeanControltotal<-matrix(, nrow = rep, ncol = max(diff))

index <- which.max(diff)

if(index < rep)
{
  x_axis_KT2000_local <- KT2000localadultcontrol[KK[index]:(KK[index+1]-1),1]
} else
{
  x_axis_KT2000_local <-KT2000localadultcontrol[KK[rep]:dim(KT2000localadultcontrol)[1],1]
}


for (i in 1:(rep-1))
{
  
  KT2000localdataset0 <- KT2000localinfect[KK[i]:(KK[i+1]-1),]
  KT2000localdataset1 <- KT2000locallarvaecontrol[KK[i]:(KK[i+1]-1),]
  KT2000localdataset2 <- KT2000localadultcontrol[KK[i]:(KK[i+1]-1),]
  KT2000localdata0 <- KT2000localdataset0[,-(which.min(KT2000localCIdistancenew[i,])+1)]
  KT2000localdataControl1 <- KT2000localdataset1[,-(which.min(KT2000localCIdistancenew[i,])+1)] 
  KT2000localdataControl2 <- KT2000localdataset2[,-(which.min(KT2000localCIdistancenew[i,])+1)] 
  ##this 1 is the time column
  KT2000localmeanInfectionSum <- as.vector(rowSums(KT2000localdata0[,2:ncol(KT2000localdata0)])/(N-1))
  KT2000localmeanControlsum <- as.vector(rowSums(1*KT2000localdataControl1[,2:ncol(KT2000localdataControl1)]+1*KT2000localdataControl2[,2:ncol(KT2000localdataControl2)])/(N-1))
  KT2000localmeanControlsum1<-approx(KT2000localdataControl1[,1],KT2000localmeanControlsum, x_axis_KT2000_local)$y
  
  KT2000localmeanInfectiontotal[i,]<-KT2000localmeanInfectionSum
  KT2000localmeanControltotal[i,]<-KT2000localmeanControlsum1
}

##last row of KT2000localmeanadultcontrol
KT2000localdataset0 <- KT2000localinfect[KK[rep]:attributes(as.matrix(KT2000locallarvaecontrol))$dim[1],]
KT2000localdataset1 <- KT2000locallarvaecontrol[KK[rep]:attributes(as.matrix(KT2000locallarvaecontrol))$dim[1],]
KT2000localdataset2 <- KT2000localadultcontrol[KK[rep]:attributes(as.matrix(KT2000localadultcontrol))$dim[1],]
KT2000localdata0 <- KT2000localdataset0[,-(which.min(KT2000localCIdistancenew[rep,])+1)] 

KT2000localdataControl1 <- KT2000localdataset1[,-(which.min(KT2000localCIdistancenew[rep,])+1)] 

KT2000localdataControl2 <- KT2000localdataset2[,-(which.min(KT2000localCIdistancenew[rep,])+1)] 
##this 1 is the time column
KT2000localmeanInfectionSum <- as.vector(rowSums(KT2000localdata0[,2:ncol(KT2000localdata0)])/(N-1))
KT2000localmeanControlsum <- as.vector(rowSums(1*KT2000localdataControl1[,2:ncol(KT2000localdataControl1)]+1*KT2000localdataControl2[,2:ncol(KT2000localdataControl2)])/(N-1))
KT2000localmeanControlsum1<-approx(KT2000localdataControl1[,1],KT2000localmeanControlsum, x_axis_KT2000_local)$y

KT2000localmeanInfectiontotal[rep,]<-KT2000localmeanInfectionSum
KT2000localmeanControltotal[rep,]<-KT2000localmeanControlsum1

KT2000localaverageInfection <- colSums(KT2000localmeanInfectiontotal)/rep

KT2000localaverageControl <- colSums(KT2000localmeanControltotal)/rep

KT2000localControlCIlow<-c()
KT2000localControlCIhigh<-c()

for(i in 1:length(KT2000localaverageControl))
{
  KT2000localControlCIlow[i]<-confidence_interval(KT2000localmeanControltotal[,i], 0.95)[1][[1]]
  KT2000localControlCIhigh[i]<-confidence_interval(KT2000localmeanControltotal[,i],0.95)[2][[1]]
}

## assign the level

CI_low_KT2000_local_control_7 <- KT2000localControlCIlow
CI_high_KT2000_local_control_7 <- KT2000localControlCIhigh
ave_KT2000_local_control_7 <- KT2000localaverageControl
ave_KT2000_local_infection_7 <- KT2000localaverageInfection
x_axis_KT2000_local_7 <- x_axis_KT2000_local

# ############################################################
#
# ##level 8
#
# ############################################################

i = 8

epsilon <- c(cont[i]+0.0001, 200.0001-cont[i])

ind <- KK_new[(replic * (i - 1) + 1) : (replic * i + 1)]


KT2000localinfect <- KT2000localinfection[ind[1]:(ind[length(ind)]-1), ]

KT2000localadultcontrol <- KT2000localcontroladult[ind[1]:(ind[length(ind)]-1), ]

KT2000locallarvaecontrol <- KT2000localcontrollarvae[ind[1]:(ind[length(ind)]-1), ]

KT2000localCIdistancenew <- KT2000localCIdistance[(replic * (i - 1) + 1): (replic * i),]


KK<-c()
for ( i in 1:dim(KT2000localadultcontrol)[1])
{
  if (KT2000localadultcontrol[i,1]==0)
    KK <-c(KK, i)
}

lastlength <- dim(KT2000localadultcontrol)[1]-KK[length(KK)]+1
diff <- c(diff(KK), lastlength)

KT2000localmeanInfectiontotal<-matrix(, nrow = rep, ncol = max(diff))
KT2000localmeanControltotal<-matrix(, nrow = rep, ncol = max(diff))

index <- which.max(diff)

if(index < rep)
{
  x_axis_KT2000_local <- KT2000localadultcontrol[KK[index]:(KK[index+1]-1),1]
} else
{
  x_axis_KT2000_local <-KT2000localadultcontrol[KK[rep]:dim(KT2000localadultcontrol)[1],1]
}


for (i in 1:(rep-1))
{
  
  KT2000localdataset0 <- KT2000localinfect[KK[i]:(KK[i+1]-1),]
  KT2000localdataset1 <- KT2000locallarvaecontrol[KK[i]:(KK[i+1]-1),]
  KT2000localdataset2 <- KT2000localadultcontrol[KK[i]:(KK[i+1]-1),]
  KT2000localdata0 <- KT2000localdataset0[,-(which.min(KT2000localCIdistancenew[i,])+1)]
  KT2000localdataControl1 <- KT2000localdataset1[,-(which.min(KT2000localCIdistancenew[i,])+1)] 
  KT2000localdataControl2 <- KT2000localdataset2[,-(which.min(KT2000localCIdistancenew[i,])+1)] 
  ##this 1 is the time column
  KT2000localmeanInfectionSum <- as.vector(rowSums(KT2000localdata0[,2:ncol(KT2000localdata0)])/(N-1))
  KT2000localmeanControlsum <- as.vector(rowSums(1*KT2000localdataControl1[,2:ncol(KT2000localdataControl1)]+1*KT2000localdataControl2[,2:ncol(KT2000localdataControl2)])/(N-1))
  KT2000localmeanControlsum1<-approx(KT2000localdataControl1[,1],KT2000localmeanControlsum, x_axis_KT2000_local)$y
  
  KT2000localmeanInfectiontotal[i,]<-KT2000localmeanInfectionSum
  KT2000localmeanControltotal[i,]<-KT2000localmeanControlsum1
}

##last row of KT2000localmeanadultcontrol
KT2000localdataset0 <- KT2000localinfect[KK[rep]:attributes(as.matrix(KT2000locallarvaecontrol))$dim[1],]
KT2000localdataset1 <- KT2000locallarvaecontrol[KK[rep]:attributes(as.matrix(KT2000locallarvaecontrol))$dim[1],]
KT2000localdataset2 <- KT2000localadultcontrol[KK[rep]:attributes(as.matrix(KT2000localadultcontrol))$dim[1],]
KT2000localdata0 <- KT2000localdataset0[,-(which.min(KT2000localCIdistancenew[rep,])+1)] 

KT2000localdataControl1 <- KT2000localdataset1[,-(which.min(KT2000localCIdistancenew[rep,])+1)] 

KT2000localdataControl2 <- KT2000localdataset2[,-(which.min(KT2000localCIdistancenew[rep,])+1)] 
##this 1 is the time column
KT2000localmeanInfectionSum <- as.vector(rowSums(KT2000localdata0[,2:ncol(KT2000localdata0)])/(N-1))
KT2000localmeanControlsum <- as.vector(rowSums(1*KT2000localdataControl1[,2:ncol(KT2000localdataControl1)]+1*KT2000localdataControl2[,2:ncol(KT2000localdataControl2)])/(N-1))
KT2000localmeanControlsum1<-approx(KT2000localdataControl1[,1],KT2000localmeanControlsum, x_axis_KT2000_local)$y

KT2000localmeanInfectiontotal[rep,]<-KT2000localmeanInfectionSum
KT2000localmeanControltotal[rep,]<-KT2000localmeanControlsum1

KT2000localaverageInfection <- colSums(KT2000localmeanInfectiontotal)/rep

KT2000localaverageControl <- colSums(KT2000localmeanControltotal)/rep

KT2000localControlCIlow<-c()
KT2000localControlCIhigh<-c()

for(i in 1:length(KT2000localaverageControl))
{
  KT2000localControlCIlow[i]<-confidence_interval(KT2000localmeanControltotal[,i], 0.95)[1][[1]]
  KT2000localControlCIhigh[i]<-confidence_interval(KT2000localmeanControltotal[,i],0.95)[2][[1]]
}

## assign the level

CI_low_KT2000_local_control_8 <- KT2000localControlCIlow
CI_high_KT2000_local_control_8 <- KT2000localControlCIhigh
ave_KT2000_local_control_8 <- KT2000localaverageControl
ave_KT2000_local_infection_8 <- KT2000localaverageInfection
x_axis_KT2000_local_8 <- x_axis_KT2000_local

# ############################################################
#
# ##level 9
#
# ############################################################


i = 9

epsilon <- c(cont[i]+0.0001, 200.0001-cont[i])

ind <- KK_new[(replic * (i - 1) + 1) : (replic * i + 1)]


KT2000localinfect <- KT2000localinfection[ind[1]:(ind[length(ind)]-1), ]

KT2000localadultcontrol <- KT2000localcontroladult[ind[1]:(ind[length(ind)]-1), ]

KT2000locallarvaecontrol <- KT2000localcontrollarvae[ind[1]:(ind[length(ind)]-1), ]

KT2000localCIdistancenew <- KT2000localCIdistance[(replic * (i - 1) + 1): (replic * i),]


KK<-c()
for ( i in 1:dim(KT2000localadultcontrol)[1])
{
  if (KT2000localadultcontrol[i,1]==0)
    KK <-c(KK, i)
}

lastlength <- dim(KT2000localadultcontrol)[1]-KK[length(KK)]+1
diff <- c(diff(KK), lastlength)

KT2000localmeanInfectiontotal<-matrix(, nrow = rep, ncol = max(diff))
KT2000localmeanControltotal<-matrix(, nrow = rep, ncol = max(diff))

index <- which.max(diff)

if(index < rep)
{
  x_axis_KT2000_local <- KT2000localadultcontrol[KK[index]:(KK[index+1]-1),1]
} else
{
  x_axis_KT2000_local <-KT2000localadultcontrol[KK[rep]:dim(KT2000localadultcontrol)[1],1]
}


for (i in 1:(rep-1))
{
  
  KT2000localdataset0 <- KT2000localinfect[KK[i]:(KK[i+1]-1),]
  KT2000localdataset1 <- KT2000locallarvaecontrol[KK[i]:(KK[i+1]-1),]
  KT2000localdataset2 <- KT2000localadultcontrol[KK[i]:(KK[i+1]-1),]
  KT2000localdata0 <- KT2000localdataset0[,-(which.min(KT2000localCIdistancenew[i,])+1)]
  KT2000localdataControl1 <- KT2000localdataset1[,-(which.min(KT2000localCIdistancenew[i,])+1)] 
  KT2000localdataControl2 <- KT2000localdataset2[,-(which.min(KT2000localCIdistancenew[i,])+1)] 
  ##this 1 is the time column
  KT2000localmeanInfectionSum <- as.vector(rowSums(KT2000localdata0[,2:ncol(KT2000localdata0)])/(N-1))
  KT2000localmeanControlsum <- as.vector(rowSums(1*KT2000localdataControl1[,2:ncol(KT2000localdataControl1)]+1*KT2000localdataControl2[,2:ncol(KT2000localdataControl2)])/(N-1))
  KT2000localmeanControlsum1<-approx(KT2000localdataControl1[,1],KT2000localmeanControlsum, x_axis_KT2000_local)$y
  
  KT2000localmeanInfectiontotal[i,]<-KT2000localmeanInfectionSum
  KT2000localmeanControltotal[i,]<-KT2000localmeanControlsum1
}

##last row of KT2000localmeanadultcontrol
KT2000localdataset0 <- KT2000localinfect[KK[rep]:attributes(as.matrix(KT2000locallarvaecontrol))$dim[1],]
KT2000localdataset1 <- KT2000locallarvaecontrol[KK[rep]:attributes(as.matrix(KT2000locallarvaecontrol))$dim[1],]
KT2000localdataset2 <- KT2000localadultcontrol[KK[rep]:attributes(as.matrix(KT2000localadultcontrol))$dim[1],]
KT2000localdata0 <- KT2000localdataset0[,-(which.min(KT2000localCIdistancenew[rep,])+1)] 

KT2000localdataControl1 <- KT2000localdataset1[,-(which.min(KT2000localCIdistancenew[rep,])+1)] 

KT2000localdataControl2 <- KT2000localdataset2[,-(which.min(KT2000localCIdistancenew[rep,])+1)] 
##this 1 is the time column
KT2000localmeanInfectionSum <- as.vector(rowSums(KT2000localdata0[,2:ncol(KT2000localdata0)])/(N-1))
KT2000localmeanControlsum <- as.vector(rowSums(1*KT2000localdataControl1[,2:ncol(KT2000localdataControl1)]+1*KT2000localdataControl2[,2:ncol(KT2000localdataControl2)])/(N-1))
KT2000localmeanControlsum1<-approx(KT2000localdataControl1[,1],KT2000localmeanControlsum, x_axis_KT2000_local)$y

KT2000localmeanInfectiontotal[rep,]<-KT2000localmeanInfectionSum
KT2000localmeanControltotal[rep,]<-KT2000localmeanControlsum1

KT2000localaverageInfection <- colSums(KT2000localmeanInfectiontotal)/rep

KT2000localaverageControl <- colSums(KT2000localmeanControltotal)/rep

KT2000localControlCIlow<-c()
KT2000localControlCIhigh<-c()

for(i in 1:length(KT2000localaverageControl))
{
  KT2000localControlCIlow[i]<-confidence_interval(KT2000localmeanControltotal[,i], 0.95)[1][[1]]
  KT2000localControlCIhigh[i]<-confidence_interval(KT2000localmeanControltotal[,i],0.95)[2][[1]]
}

## assign the level

CI_low_KT2000_local_control_9 <- KT2000localControlCIlow
CI_high_KT2000_local_control_9 <- KT2000localControlCIhigh
ave_KT2000_local_control_9 <- KT2000localaverageControl
ave_KT2000_local_infection_9 <- KT2000localaverageInfection
x_axis_KT2000_local_9 <- x_axis_KT2000_local

# ###########################################################
#
# ##level 10
#
# ############################################################

i = 10

epsilon <- c(cont[i]+0.0001, 200.0001-cont[i])

ind <- KK_new[(replic * (i - 1) + 1) : (replic * i + 1)]


KT2000localinfect <- KT2000localinfection[ind[1]:(ind[length(ind)]-1), ]

KT2000localadultcontrol <- KT2000localcontroladult[ind[1]:(ind[length(ind)]-1), ]

KT2000locallarvaecontrol <- KT2000localcontrollarvae[ind[1]:(ind[length(ind)]-1), ]

KT2000localCIdistancenew <- KT2000localCIdistance[(replic * (i - 1) + 1): (replic * i),]


KK<-c()
for ( i in 1:dim(KT2000localadultcontrol)[1])
{
  if (KT2000localadultcontrol[i,1]==0)
    KK <-c(KK, i)
}

lastlength <- dim(KT2000localadultcontrol)[1]-KK[length(KK)]+1
diff <- c(diff(KK), lastlength)

KT2000localmeanInfectiontotal<-matrix(, nrow = rep, ncol = max(diff))
KT2000localmeanControltotal<-matrix(, nrow = rep, ncol = max(diff))

index <- which.max(diff)

if(index < rep)
{
  x_axis_KT2000_local <- KT2000localadultcontrol[KK[index]:(KK[index+1]-1),1]
} else
{
  x_axis_KT2000_local <-KT2000localadultcontrol[KK[rep]:dim(KT2000localadultcontrol)[1],1]
}


for (i in 1:(rep-1))
{
  
  KT2000localdataset0 <- KT2000localinfect[KK[i]:(KK[i+1]-1),]
  KT2000localdataset1 <- KT2000locallarvaecontrol[KK[i]:(KK[i+1]-1),]
  KT2000localdataset2 <- KT2000localadultcontrol[KK[i]:(KK[i+1]-1),]
  KT2000localdata0 <- KT2000localdataset0[,-(which.min(KT2000localCIdistancenew[i,])+1)]
  KT2000localdataControl1 <- KT2000localdataset1[,-(which.min(KT2000localCIdistancenew[i,])+1)] 
  KT2000localdataControl2 <- KT2000localdataset2[,-(which.min(KT2000localCIdistancenew[i,])+1)] 
  ##this 1 is the time column
  KT2000localmeanInfectionSum <- as.vector(rowSums(KT2000localdata0[,2:ncol(KT2000localdata0)])/(N-1))
  KT2000localmeanControlsum <- as.vector(rowSums(1*KT2000localdataControl1[,2:ncol(KT2000localdataControl1)]+1*KT2000localdataControl2[,2:ncol(KT2000localdataControl2)])/(N-1))
  KT2000localmeanControlsum1<-approx(KT2000localdataControl1[,1],KT2000localmeanControlsum, x_axis_KT2000_local)$y
  
  KT2000localmeanInfectiontotal[i,]<-KT2000localmeanInfectionSum
  KT2000localmeanControltotal[i,]<-KT2000localmeanControlsum1
}

##last row of KT2000localmeanadultcontrol
KT2000localdataset0 <- KT2000localinfect[KK[rep]:attributes(as.matrix(KT2000locallarvaecontrol))$dim[1],]
KT2000localdataset1 <- KT2000locallarvaecontrol[KK[rep]:attributes(as.matrix(KT2000locallarvaecontrol))$dim[1],]
KT2000localdataset2 <- KT2000localadultcontrol[KK[rep]:attributes(as.matrix(KT2000localadultcontrol))$dim[1],]
KT2000localdata0 <- KT2000localdataset0[,-(which.min(KT2000localCIdistancenew[rep,])+1)] 

KT2000localdataControl1 <- KT2000localdataset1[,-(which.min(KT2000localCIdistancenew[rep,])+1)] 

KT2000localdataControl2 <- KT2000localdataset2[,-(which.min(KT2000localCIdistancenew[rep,])+1)] 
##this 1 is the time column
KT2000localmeanInfectionSum <- as.vector(rowSums(KT2000localdata0[,2:ncol(KT2000localdata0)])/(N-1))
KT2000localmeanControlsum <- as.vector(rowSums(1*KT2000localdataControl1[,2:ncol(KT2000localdataControl1)]+1*KT2000localdataControl2[,2:ncol(KT2000localdataControl2)])/(N-1))
KT2000localmeanControlsum1<-approx(KT2000localdataControl1[,1],KT2000localmeanControlsum, x_axis_KT2000_local)$y

KT2000localmeanInfectiontotal[rep,]<-KT2000localmeanInfectionSum
KT2000localmeanControltotal[rep,]<-KT2000localmeanControlsum1

KT2000localaverageInfection <- colSums(KT2000localmeanInfectiontotal)/rep

KT2000localaverageControl <- colSums(KT2000localmeanControltotal)/rep

KT2000localControlCIlow<-c()
KT2000localControlCIhigh<-c()

for(i in 1:length(KT2000localaverageControl))
{
  KT2000localControlCIlow[i]<-confidence_interval(KT2000localmeanControltotal[,i], 0.95)[1][[1]]
  KT2000localControlCIhigh[i]<-confidence_interval(KT2000localmeanControltotal[,i],0.95)[2][[1]]
}

## assign the level

CI_low_KT2000_local_control_10 <- KT2000localControlCIlow
CI_high_KT2000_local_control_10 <- KT2000localControlCIhigh
ave_KT2000_local_control_10 <- KT2000localaverageControl
ave_KT2000_local_infection_10 <- KT2000localaverageInfection
x_axis_KT2000_local_10 <- x_axis_KT2000_local

############################################################

##level 11

############################################################

i = 11

epsilon <- c(cont[i]+0.0001, 200.0001-cont[i])

ind <- KK_new[(replic * (i - 1) + 1) : (replic * i + 1)]


KT2000localinfect <- KT2000localinfection[ind[1]:(ind[length(ind)]-1), ]

KT2000localadultcontrol <- KT2000localcontroladult[ind[1]:(ind[length(ind)]-1), ]

KT2000locallarvaecontrol <- KT2000localcontrollarvae[ind[1]:(ind[length(ind)]-1), ]

KT2000localCIdistancenew <- KT2000localCIdistance[(replic * (i - 1) + 1): (replic * i),]


KK<-c()
for ( i in 1:dim(KT2000localadultcontrol)[1])
{
  if (KT2000localadultcontrol[i,1]==0)
    KK <-c(KK, i)
}

lastlength <- dim(KT2000localadultcontrol)[1]-KK[length(KK)]+1
diff <- c(diff(KK), lastlength)

KT2000localmeanInfectiontotal<-matrix(, nrow = rep, ncol = max(diff))
KT2000localmeanControltotal<-matrix(, nrow = rep, ncol = max(diff))

index <- which.max(diff)

if(index < rep)
{
  x_axis_KT2000_local <- KT2000localadultcontrol[KK[index]:(KK[index+1]-1),1]
} else
{
  x_axis_KT2000_local <-KT2000localadultcontrol[KK[rep]:dim(KT2000localadultcontrol)[1],1]
}


for (i in 1:(rep-1))
{
  
  KT2000localdataset0 <- KT2000localinfect[KK[i]:(KK[i+1]-1),]
  KT2000localdataset1 <- KT2000locallarvaecontrol[KK[i]:(KK[i+1]-1),]
  KT2000localdataset2 <- KT2000localadultcontrol[KK[i]:(KK[i+1]-1),]
  KT2000localdata0 <- KT2000localdataset0[,-(which.min(KT2000localCIdistancenew[i,])+1)]
  KT2000localdataControl1 <- KT2000localdataset1[,-(which.min(KT2000localCIdistancenew[i,])+1)] 
  KT2000localdataControl2 <- KT2000localdataset2[,-(which.min(KT2000localCIdistancenew[i,])+1)] 
  ##this 1 is the time column
  KT2000localmeanInfectionSum <- as.vector(rowSums(KT2000localdata0[,2:ncol(KT2000localdata0)])/(N-1))
  KT2000localmeanControlsum <- as.vector(rowSums(1*KT2000localdataControl1[,2:ncol(KT2000localdataControl1)]+1*KT2000localdataControl2[,2:ncol(KT2000localdataControl2)])/(N-1))
  KT2000localmeanControlsum1<-approx(KT2000localdataControl1[,1],KT2000localmeanControlsum, x_axis_KT2000_local)$y
  
  KT2000localmeanInfectiontotal[i,]<-KT2000localmeanInfectionSum
  KT2000localmeanControltotal[i,]<-KT2000localmeanControlsum1
}

##last row of KT2000localmeanadultcontrol
KT2000localdataset0 <- KT2000localinfect[KK[rep]:attributes(as.matrix(KT2000locallarvaecontrol))$dim[1],]
KT2000localdataset1 <- KT2000locallarvaecontrol[KK[rep]:attributes(as.matrix(KT2000locallarvaecontrol))$dim[1],]
KT2000localdataset2 <- KT2000localadultcontrol[KK[rep]:attributes(as.matrix(KT2000localadultcontrol))$dim[1],]
KT2000localdata0 <- KT2000localdataset0[,-(which.min(KT2000localCIdistancenew[rep,])+1)] 

KT2000localdataControl1 <- KT2000localdataset1[,-(which.min(KT2000localCIdistancenew[rep,])+1)] 

KT2000localdataControl2 <- KT2000localdataset2[,-(which.min(KT2000localCIdistancenew[rep,])+1)] 
##this 1 is the time column
KT2000localmeanInfectionSum <- as.vector(rowSums(KT2000localdata0[,2:ncol(KT2000localdata0)])/(N-1))
KT2000localmeanControlsum <- as.vector(rowSums(1*KT2000localdataControl1[,2:ncol(KT2000localdataControl1)]+1*KT2000localdataControl2[,2:ncol(KT2000localdataControl2)])/(N-1))
KT2000localmeanControlsum1<-approx(KT2000localdataControl1[,1],KT2000localmeanControlsum, x_axis_KT2000_local)$y

KT2000localmeanInfectiontotal[rep,]<-KT2000localmeanInfectionSum
KT2000localmeanControltotal[rep,]<-KT2000localmeanControlsum1

KT2000localaverageInfection <- colSums(KT2000localmeanInfectiontotal)/rep

KT2000localaverageControl <- colSums(KT2000localmeanControltotal)/rep

KT2000localControlCIlow<-c()
KT2000localControlCIhigh<-c()

for(i in 1:length(KT2000localaverageControl))
{
  KT2000localControlCIlow[i]<-confidence_interval(KT2000localmeanControltotal[,i], 0.95)[1][[1]]
  KT2000localControlCIhigh[i]<-confidence_interval(KT2000localmeanControltotal[,i],0.95)[2][[1]]
}

## assign the level

CI_low_KT2000_local_control_11 <- KT2000localControlCIlow
CI_high_KT2000_local_control_11 <- KT2000localControlCIhigh
ave_KT2000_local_control_11 <- KT2000localaverageControl
ave_KT2000_local_infection_11 <- KT2000localaverageInfection
x_axis_KT2000_local_11 <- x_axis_KT2000_local

############################################################


############################################################################################

ylimup1 <- max(ave_KT2000_local_infection_1, ave_KT2000_local_infection_2, ave_KT2000_local_infection_3, ave_KT2000_local_infection_4, ave_KT2000_local_infection_5, ave_KT2000_local_infection_6, ave_KT2000_local_infection_7, ave_KT2000_local_infection_8, ave_KT2000_local_infection_9, ave_KT2000_local_infection_10, ave_KT2000_local_infection_11)
ylimlow1 <- min(ave_KT2000_local_infection_1, ave_KT2000_local_infection_2, ave_KT2000_local_infection_3, ave_KT2000_local_infection_4, ave_KT2000_local_infection_5, ave_KT2000_local_infection_6, ave_KT2000_local_infection_7, ave_KT2000_local_infection_8, ave_KT2000_local_infection_9, ave_KT2000_local_infection_10, ave_KT2000_local_infection_11)

tiff("KT2000_local_infectiondynamics-strengthtime-10-20.tiff", width=10,height=10, units='in',res=600)


plot(x_axis_KT2000_local_1, ave_KT2000_local_infection_1, xlab = "Time", ylab = "Total infection", main = "All levels at K = 2000 local", type = "l", col = "dark blue", ylim = c(ylimlow1,ylimup1))
# points(x_axis_KT2000_local_1, CI_low_KT2000_local_infection_1, type = "l", col = "dark blue", lty = 2)
# points(x_axis_KT2000_local_1, CI_high_KT2000_local_infection_1, type = "l", col = "dark blue", lty = 2)

points(x_axis_KT2000_local_2, ave_KT2000_local_infection_2, type = "l", col = "blue")


points(x_axis_KT2000_local_3, ave_KT2000_local_infection_3, type = "l", col = "light blue")


points(x_axis_KT2000_local_4, ave_KT2000_local_infection_4, type = "l", col = "pink")


points(x_axis_KT2000_local_5, ave_KT2000_local_infection_5, type = "l", col = "orange")



points(x_axis_KT2000_local_6, ave_KT2000_local_infection_6, type = "l", col = "red")

# 
points(x_axis_KT2000_local_7, ave_KT2000_local_infection_7, type = "l", col = "light pink")

points(x_axis_KT2000_local_8, ave_KT2000_local_infection_8, type = "l", col = "pink")

points(x_axis_KT2000_local_9, ave_KT2000_local_infection_9, type = "l", col = "orange")

points(x_axis_KT2000_local_10, ave_KT2000_local_infection_10, type = "l", col = "red")


points(x_axis_KT2000_local_11, ave_KT2000_local_infection_11, type = "l", col = "dark red")

dev.off()
# 



ylimup <- max(ave_KT2000_local_control_1, ave_KT2000_local_control_2, ave_KT2000_local_control_3, ave_KT2000_local_control_4, ave_KT2000_local_control_5, ave_KT2000_local_control_6, ave_KT2000_local_control_7, ave_KT2000_local_control_8, ave_KT2000_local_control_9, ave_KT2000_local_control_10, ave_KT2000_local_control_11)
ylimlow <- min(ave_KT2000_local_control_1, ave_KT2000_local_control_2, ave_KT2000_local_control_3, ave_KT2000_local_control_4, ave_KT2000_local_control_5, ave_KT2000_local_control_6, ave_KT2000_local_control_7, ave_KT2000_local_control_8, ave_KT2000_local_control_9, ave_KT2000_local_control_10, ave_KT2000_local_control_11)

tiff("KT2000_local_controldynamics-10-20.tiff", width=10,height=10, units='in',res=600)


plot(x_axis_KT2000_local_1, ave_KT2000_local_control_1, xlab = "Time", ylab = "Total Control through 'strength effect'", main = "All levels at K =2000 local", type = "l", col = "dark blue", ylim = c(ylimlow,ylimup))
# points(x_axis_KT2000_local_1, CI_low_KT2000_local_control_1, type = "l", col = "dark blue", lty = 2)
# points(x_axis_KT2000_local_1, CI_high_KT2000_local_control_1, type = "l", col = "dark blue", lty = 2)

points(x_axis_KT2000_local_2, ave_KT2000_local_control_2, type = "l", col = "blue")
points(x_axis_KT2000_local_2, CI_low_KT2000_local_control_2, type = "l", col = "blue", lty = 2)
points(x_axis_KT2000_local_2, CI_high_KT2000_local_control_2, type = "l", col = "blue", lty = 2)


points(x_axis_KT2000_local_3, ave_KT2000_local_control_3, type = "l", col = "light blue")
points(x_axis_KT2000_local_3, CI_low_KT2000_local_control_3, type = "l", col = "light blue", lty = 2)
points(x_axis_KT2000_local_3, CI_high_KT2000_local_control_3, type = "l", col = "light blue", lty = 2)


points(x_axis_KT2000_local_4, ave_KT2000_local_control_4, type = "l", col = "pink")
points(x_axis_KT2000_local_4, CI_low_KT2000_local_control_4, type = "l", col = "pink", lty = 2)
points(x_axis_KT2000_local_4, CI_high_KT2000_local_control_4, type = "l", col = "pink", lty = 2)


points(x_axis_KT2000_local_5, ave_KT2000_local_control_5, type = "l", col = "orange")
points(x_axis_KT2000_local_5, CI_low_KT2000_local_control_5, type = "l", col = "orange", lty = 2)
points(x_axis_KT2000_local_5, CI_high_KT2000_local_control_5, type = "l", col = "orange", lty = 2)



points(x_axis_KT2000_local_6, ave_KT2000_local_control_6, type = "l", col = "red")
points(x_axis_KT2000_local_6, CI_low_KT2000_local_control_6, type = "l", col = "red", lty = 2)
points(x_axis_KT2000_local_6, CI_high_KT2000_local_control_6, type = "l", col = "red", lty = 2)

# 
points(x_axis_KT2000_local_7, ave_KT2000_local_control_7, type = "l", col = "light pink")
points(x_axis_KT2000_local_7, CI_low_KT2000_local_control_7, type = "l", col = "light pink", lty = 2)
points(x_axis_KT2000_local_7, CI_high_KT2000_local_control_7, type = "l", col = "light pink", lty = 2)

points(x_axis_KT2000_local_8, ave_KT2000_local_control_8, type = "l", col = "pink")
points(x_axis_KT2000_local_8, CI_low_KT2000_local_control_8, type = "l", col = "pink", lty = 2)
points(x_axis_KT2000_local_8, CI_high_KT2000_local_control_8, type = "l", col = "pink", lty = 2)

points(x_axis_KT2000_local_9, ave_KT2000_local_control_9, type = "l", col = "orange")
points(x_axis_KT2000_local_9, CI_low_KT2000_local_control_9, type = "l", col = "orange", lty = 2)
points(x_axis_KT2000_local_9, CI_high_KT2000_local_control_9, type = "l", col = "orange", lty = 2)

points(x_axis_KT2000_local_10, ave_KT2000_local_control_10, type = "l", col = "red")
points(x_axis_KT2000_local_10, CI_low_KT2000_local_control_10, type = "l", col = "red", lty = 2)
points(x_axis_KT2000_local_10, CI_high_KT2000_local_control_10, type = "l", col = "red", lty = 2)


points(x_axis_KT2000_local_11, ave_KT2000_local_control_11, type = "l", col = "dark red")
points(x_axis_KT2000_local_11, CI_low_KT2000_local_control_11, type = "l", col = "dark red", lty = 2)
points(x_axis_KT2000_local_11, CI_high_KT2000_local_control_11, type = "l", col = "dark red", lty = 2)

dev.off()

middle <- 601 # pick up the time point at equlibrium and generate the plot across different levels of adult concerns

ave_KS2000_local_control_middle <- c(ave_KS2000_local_control_1[middle], ave_KS2000_local_control_2[middle], ave_KS2000_local_control_3[middle], ave_KS2000_local_control_4[middle], ave_KS2000_local_control_5[middle], ave_KS2000_local_control_6[middle], ave_KS2000_local_control_7[middle], ave_KS2000_local_control_8[middle], ave_KS2000_local_control_9[middle], ave_KS2000_local_control_10[middle], ave_KS2000_local_control_11[middle])

CIlow_KS2000_local_control_middle <- c(CI_low_KS2000_local_control_1[middle], CI_low_KS2000_local_control_2[middle], CI_low_KS2000_local_control_3[middle], CI_low_KS2000_local_control_4[middle], CI_low_KS2000_local_control_5[middle], CI_low_KS2000_local_control_6[middle], CI_low_KS2000_local_control_7[middle], CI_low_KS2000_local_control_8[middle], CI_low_KS2000_local_control_9[middle], CI_low_KS2000_local_control_10[middle], CI_low_KS2000_local_control_11[middle])

CIhigh_KS2000_local_control_middle <- c(CI_high_KS2000_local_control_1[middle], CI_high_KS2000_local_control_2[middle], CI_high_KS2000_local_control_3[middle], CI_high_KS2000_local_control_4[middle], CI_high_KS2000_local_control_5[middle], CI_high_KS2000_local_control_6[middle], CI_high_KS2000_local_control_7[middle], CI_high_KS2000_local_control_8[middle], CI_high_KS2000_local_control_9[middle], CI_high_KS2000_local_control_10[middle], CI_high_KS2000_local_control_11[middle]) 

ave_KT2000_local_control_middle <- c(ave_KT2000_local_control_1[middle], ave_KT2000_local_control_2[middle], ave_KT2000_local_control_3[middle], ave_KT2000_local_control_4[middle], ave_KT2000_local_control_5[middle], ave_KT2000_local_control_6[middle], ave_KT2000_local_control_7[middle], ave_KT2000_local_control_8[middle], ave_KT2000_local_control_9[middle], ave_KT2000_local_control_10[middle], ave_KT2000_local_control_11[middle])

CIlow_KT2000_local_control_middle <- c(CI_low_KT2000_local_control_1[middle], CI_low_KT2000_local_control_2[middle], CI_low_KT2000_local_control_3[middle], CI_low_KT2000_local_control_4[middle], CI_low_KT2000_local_control_5[middle], CI_low_KT2000_local_control_6[middle], CI_low_KT2000_local_control_7[middle], CI_low_KT2000_local_control_8[middle], CI_low_KT2000_local_control_9[middle], CI_low_KT2000_local_control_10[middle], CI_low_KT2000_local_control_11[middle])

CIhigh_KT2000_local_control_middle <- c(CI_high_KT2000_local_control_1[middle], CI_high_KT2000_local_control_2[middle], CI_high_KT2000_local_control_3[middle], CI_high_KT2000_local_control_4[middle], CI_high_KT2000_local_control_5[middle], CI_high_KT2000_local_control_6[middle], CI_high_KT2000_local_control_7[middle], CI_high_KT2000_local_control_8[middle], CI_high_KT2000_local_control_9[middle], CI_high_KT2000_local_control_10[middle], CI_high_KT2000_local_control_11[middle]) 

ave_KS2000_local_infection_middle <- c(ave_KS2000_local_infection_1[middle], ave_KS2000_local_infection_2[middle], ave_KS2000_local_infection_3[middle], ave_KS2000_local_infection_4[middle], ave_KS2000_local_infection_5[middle], ave_KS2000_local_infection_6[middle], ave_KS2000_local_infection_7[middle], ave_KS2000_local_infection_8[middle], ave_KS2000_local_infection_9[middle], ave_KS2000_local_infection_10[middle], ave_KS2000_local_infection_11[middle])

CIlow_KS2000_local_infection_middle <- c(CI_low_KS2000_local_infection_1[middle], CI_low_KS2000_local_infection_2[middle], CI_low_KS2000_local_infection_3[middle], CI_low_KS2000_local_infection_4[middle], CI_low_KS2000_local_infection_5[middle], CI_low_KS2000_local_infection_6[middle], CI_low_KS2000_local_infection_7[middle], CI_low_KS2000_local_infection_8[middle], CI_low_KS2000_local_infection_9[middle], CI_low_KS2000_local_infection_10[middle], CI_low_KS2000_local_infection_11[middle])

CIhigh_KS2000_local_infection_middle <- c(CI_high_KS2000_local_infection_1[middle], CI_high_KS2000_local_infection_2[middle], CI_high_KS2000_local_infection_3[middle], CI_high_KS2000_local_infection_4[middle], CI_high_KS2000_local_infection_5[middle], CI_high_KS2000_local_infection_6[middle], CI_high_KS2000_local_infection_7[middle], CI_high_KS2000_local_infection_8[middle], CI_high_KS2000_local_infection_9[middle], CI_high_KS2000_local_infection_10[middle], CI_high_KS2000_local_infection_11[middle]) 

ave_KT2000_local_infection_middle <- c(ave_KT2000_local_infection_1[middle], ave_KT2000_local_infection_2[middle], ave_KT2000_local_infection_3[middle], ave_KT2000_local_infection_4[middle], ave_KT2000_local_infection_5[middle], ave_KT2000_local_infection_6[middle], ave_KT2000_local_infection_7[middle], ave_KT2000_local_infection_8[middle], ave_KT2000_local_infection_9[middle], ave_KT2000_local_infection_10[middle], ave_KT2000_local_infection_11[middle])

CIlow_KT2000_local_infection_middle <- c(CI_low_KT2000_local_infection_1[middle], CI_low_KT2000_local_infection_2[middle], CI_low_KT2000_local_infection_3[middle], CI_low_KT2000_local_infection_4[middle], CI_low_KT2000_local_infection_5[middle], CI_low_KT2000_local_infection_6[middle], CI_low_KT2000_local_infection_7[middle], CI_low_KT2000_local_infection_8[middle], CI_low_KT2000_local_infection_9[middle], CI_low_KT2000_local_infection_10[middle], CI_low_KT2000_local_infection_11[middle])

CIhigh_KT2000_local_infection_middle <- c(CI_high_KT2000_local_infection_1[middle], CI_high_KT2000_local_infection_2[middle], CI_high_KT2000_local_infection_3[middle], CI_high_KT2000_local_infection_4[middle], CI_high_KT2000_local_infection_5[middle], CI_high_KT2000_local_infection_6[middle], CI_high_KT2000_local_infection_7[middle], CI_high_KT2000_local_infection_8[middle], CI_high_KT2000_local_infection_9[middle], CI_high_KT2000_local_infection_10[middle], CI_high_KT2000_local_infection_11[middle]) 

####################################################################################################################################

 ## Results from NO Control at three levels of breeding capacity. This section is used for calculating control efficacy in Figure 4.
 
####################################################################################################################################
### K = 500

setwd("~\\SF-local-N-9-p-0.01-t-300-K=500-nocontrol")

Ks500nocontrollocalInfection <- read.csv("2-a1--a2--g1--g2--e1--e2--INFECTED-HUMANS.csv",header=FALSE)
Ks500nocontrollocaldistance <- read.csv("2-a1--a2--g1--g2--e1--e2--DISTANCE-PATCH.csv",header = FALSE)
Ks500nocontrollocaldistance_new <- apply(Ks500nocontrollocaldistance,2,function(x){rep(x,each = 601)})

pp <- apply(Ks500nocontrollocaldistance_new,1,function(x){which.min(x)+1})

c<-data.frame(matrix(NA,nrow(Ks500nocontrollocalInfection),(ncol(Ks500nocontrollocalInfection)-1)))

for(i in 1:nrow(Ks500nocontrollocalInfection))
{
  c[i,] = Ks500nocontrollocalInfection[i,-pp[i]]  
  
}

c1 <- c[,-1]

newKs500nocontrolglobalmeaninfection <- apply(c1,1,mean)
newKs500nocontrollocalmeaninfection <- newKs500nocontrolglobalmeaninfection
newKs500nocontrolneighbormeaninfection <- newKs500nocontrolglobalmeaninfection

K500globalnocontrol <- c()

for (i in 1:601)
{
  q = 0
  
  for(j in 0:(rep-1))
  {
    
    q <- sum(q, newKs500nocontrolglobalmeaninfection[i+601*j])
  } 
  
  K500globalnocontrol[i]<-q/rep
  
}

K500localnocontrol <- K500globalnocontrol
K500neighbornocontrol <- K500globalnocontrol

#################################################################
## K = 800

setwd("~\\SF-local-N-9-p-0.01-t-300-K=800-nocontrol")

Ks800nocontrollocalInfection <- read.csv("2-a1--a2--g1--g2--e1--e2--INFECTED-HUMANS.csv",header=FALSE)
Ks800nocontrollocaldistance <- read.csv("2-a1--a2--g1--g2--e1--e2--DISTANCE-PATCH.csv",header = FALSE)
Ks800nocontrollocaldistance_new <- apply(Ks800nocontrollocaldistance,2,function(x){rep(x,each = 601)})

pp <- apply(Ks800nocontrollocaldistance_new,1,function(x){which.min(x)+1})

c<-data.frame(matrix(NA,nrow(Ks800nocontrollocalInfection),(ncol(Ks800nocontrollocalInfection)-1)))

for(i in 1:nrow(Ks800nocontrollocalInfection))
{
  c[i,] = Ks800nocontrollocalInfection[i,-pp[i]]  
  
}

c1 <- c[,-1]

newKs800nocontrolglobalmeaninfection <- apply(c1,1,mean)

newKs800nocontrollocalmeaninfection <- newKs800nocontrolglobalmeaninfection
newKs800nocontrolneighbormeaninfection <- newKs800nocontrolglobalmeaninfection

K800globalnocontrol <- c()

for (i in 1:601)
{
  q = 0
  
  for(j in 0:(rep-1))
  {
    
    q <- sum(q, newKs800nocontrolglobalmeaninfection[i+601*j])
  } 
  
  K800globalnocontrol[i]<-q/rep
  
}

K800localnocontrol <- K800globalnocontrol
K800neighbornocontrol <- K800globalnocontrol

#####################################################################
### K = 2000

setwd("~\\SF-local-N-9-p-0.01-t-300-K=2000-nocontrol")

Ks2000nocontrollocalInfection <- read.csv("2-a1--a2--g1--g2--e1--e2--INFECTED-HUMANS.csv",header=FALSE)
Ks2000nocontrollocaldistance <- read.csv("2-a1--a2--g1--g2--e1--e2--DISTANCE-PATCH.csv",header = FALSE)
Ks2000nocontrollocaldistance_new <- apply(Ks2000nocontrollocaldistance,2,function(x){rep(x,each = 601)})

pp <- apply(Ks2000nocontrollocaldistance_new,1,function(x){which.min(x)+1})

c<-data.frame(matrix(NA,nrow(Ks2000nocontrollocalInfection),(ncol(Ks2000nocontrollocalInfection)-1)))

for(i in 1:nrow(Ks2000nocontrollocalInfection))
{
  c[i,] = Ks2000nocontrollocalInfection[i,-pp[i]]  
  
}

c1 <- c[,-1]

newKs2000nocontrolglobalmeaninfection <- apply(c1,1,mean)
newKs2000nocontrollocalmeaninfection <- newKs2000nocontrolglobalmeaninfection
newKs2000nocontrolneighbormeaninfection <- newKs2000nocontrolglobalmeaninfection

K2000globalnocontrol <- c()

for (i in 1:601)
{
  q = 0
  
  for(j in 0:(rep-1))
  {
    
    q <- sum(q, newKs2000nocontrolglobalmeaninfection[i+601*j])
  } 
  
  K2000globalnocontrol[i]<-q/rep
  
}

K2000localnocontrol <- K2000globalnocontrol
K2000neighbornocontrol <- K2000globalnocontrol


K500nocontrol = rep(K500localnocontrol[601],length(cont))
K800nocontrol = rep(K800localnocontrol[601],length(cont))
K2000nocontrol = rep(K2000localnocontrol[601],length(cont))


jpeg("Figure_4.jpeg", width=10,height=10, units='in',res=600)

par(mfrow=c(3,3))
par(mar=c(2,3,3,3))

plot(cont, ave_KT500_local_infection_middle, type = "l", lwd = 2, xlab = "Levels of Adult Concern", ylab = "Average Infection at time 300",col="red", ylim = c(min(ave_KT500_local_infection_middle), max(ave_KT500_local_infection_middle)))
points(cont, ave_KT500_neighbor_infection_middle, type = "l", col = "blue")
points(cont, ave_KT500_global_infection_middle, type = "l", col = "green")

plot(cont, ave_KT500_local_control_middle, type = "l", lwd = 2, xlab = "Levels of Adult Concern", ylab = "Total Control at time 300",col="red", ylim = c(min(ave_KT500_local_control_middle), max(ave_KT500_local_control_middle)))
points(cont, ave_KT500_neighbor_control_middle, type = "l", col = "blue")
points(cont, ave_KT500_global_control_middle, type = "l", col = "green")


subplot(cont[2:10], ave_KT500_local_infection_middle[2:10], mgp = c(1,0.4,0), pars = list(mar=c(1.0, 0, 1.0, 0)+0.1), col ="red", ylim =c(min(ave_KT500_local_infection_middle[2:10]),max(ave_KT500_local_infection_middle[2:10])))
points(cont[2:10], ave_KT500_neighbor_infection_middle[2:10], type ="l",  col = "blue")
points(cont[2:10], ave_KT500_global_infection_middle[2:10], col = "green", type = "l")

plot(cont, (K500nocontrol-ave_KT500_local_infection_middle)/ave_KT500_local_control_middle, type = "l", lwd = 2, xlab = "Levels of Adult Concern", ylab = "Control Efficacy at time 300",col="red", ylim = c(min((K500nocontrol-ave_KT500_local_infection_middle)/ave_KT500_local_control_middle), max((K500nocontrol-ave_KT500_local_infection_middle)/ave_KT500_local_control_middle)))
points(cont, (K500nocontrol-ave_KT500_neighbor_infection_middle)/ave_KT500_neighbor_control_middle, type = "l", col = "blue")
points(cont, (K500nocontrol-ave_KT500_global_infection_middle)/ave_KT500_global_control_middle, type = "l", col = "green")

plot(cont, ave_KT800_local_infection_middle, type = "l", lwd = 2, xlab = "Levels of Adult Concern", ylab = "Average Infection at time 300",col="red", ylim = c(min(ave_KT800_local_infection_middle), max(ave_KT800_local_infection_middle)))
points(cont, ave_KT800_neighbor_infection_middle, type = "l", col = "blue")
points(cont, ave_KT800_global_infection_middle, type = "l", col = "green")

plot(cont, ave_KT800_local_control_middle, type = "l", lwd = 2, xlab = "Levels of Adult Concern", ylab = "Total Control at time 300",col="red", ylim = c(min(ave_KT800_local_control_middle, ave_KT800_global_control_middle, ave_KT800_neighbor_control_middle), max(ave_KT800_local_control_middle)))
points(cont, ave_KT800_neighbor_control_middle, type = "l", col = "blue")
points(cont, ave_KT800_global_control_middle, type = "l", col = "green")

subplot(cont[2:10], ave_KT800_local_infection_middle[2:10], col ="red", ylim =c(min(ave_KT800_local_infection_middle[2:10]),max(ave_KT800_local_infection_middle[2:10])))
points(cont[2:10], ave_KT800_neighbor_infection_middle[2:10], type = "l", col = "blue")
points(cont[2:10], ave_KT800_global_infection_middle[2:10], type= "l",col = "green")


plot(cont, (K800nocontrol-ave_KT800_local_infection_middle)/ave_KT800_local_control_middle, type = "l", lwd = 2, xlab = "Levels of Adult Concern", ylab = "Control Efficacy at time 300",col="red", ylim = c(min((K800nocontrol-ave_KT800_local_infection_middle)/ave_KT800_local_control_middle), max((K800nocontrol-ave_KT800_local_infection_middle)/ave_KT800_local_control_middle)))
points(cont, (K800nocontrol-ave_KT800_neighbor_infection_middle)/ave_KT800_neighbor_control_middle, type = "l", col = "blue")
points(cont, (K800nocontrol-ave_KT800_global_infection_middle)/ave_KT800_global_control_middle, type = "l", col = "green")

plot(cont, ave_KT2000_local_infection_middle, type = "l", lwd = 2, xlab = "Levels of Adult Concern", ylab = "Average Infection at time 300",col="red", ylim = c(min(ave_KT2000_local_infection_middle), max(ave_KT2000_local_infection_middle)))
points(cont, ave_KT2000_neighbor_infection_middle, type = "l", col = "blue")
points(cont, ave_KT2000_global_infection_middle, type = "l", col = "green")

plot(cont, ave_KT2000_local_control_middle, type = "l", lwd = 2, xlab = "Levels of Adult Concern", ylab = "Total Control at time 300",col="red", ylim = c(min(ave_KT2000_local_control_middle), max(ave_KT2000_local_control_middle)))
points(cont, ave_KT2000_neighbor_control_middle, type = "l", col = "blue")
points(cont, ave_KT2000_global_control_middle, type = "l", col = "green")


plot(cont, (K2000nocontrol-ave_KT2000_local_infection_middle)/ave_KT2000_local_control_middle, type = "l", lwd = 2, xlab = "Levels of Adult Concern", ylab = "Control Efficacy at time 300",col="red", ylim = c(min((K2000nocontrol-ave_KT2000_local_infection_middle)/ave_KT2000_local_control_middle), max((K2000nocontrol-ave_KT2000_local_infection_middle)/ave_KT2000_local_control_middle)))
points(cont, (K2000nocontrol-ave_KT2000_neighbor_infection_middle)/ave_KT2000_neighbor_control_middle, type = "l", col = "blue")
points(cont, (K2000nocontrol-ave_KT2000_global_infection_middle)/ave_KT2000_global_control_middle, type = "l", col = "green")


dev.off()


